'use strict';
(() => {
 const dialog=document.querySelector('#demo-dialog'),content=document.querySelector('#demo-content'),title=document.querySelector('#demo-title');let opener,cleanup=()=>{};
 document.querySelector('#close-dialog').addEventListener('click',()=>dialog.close());
 dialog.addEventListener('close',()=>{cleanup();cleanup=()=>{};opener?.focus();});
 function setup(kind){
 if(kind==='bouquet'){
 title.textContent='Rangkai Buket';
 content.innerHTML=`<p>Buket kecil, pesan hangat. Pilih pembungkus lalu tuliskan ucapanmu.</p><div class="demo-preview bouquet-preview" id="bouquet-preview"><img src="assets/lily.svg" alt=""><img src="assets/lily.svg" alt=""><img src="assets/lily.svg" alt=""><p id="bouquet-message">Semoga harimu mekar indah ♡</p></div><label for="wrap-color">Warna pembungkus</label><select id="wrap-color"><option value="#f0bfd2">Pink sakura</option><option value="#c3d6b7">Hijau sage</option><option value="#d9cceb">Lavender</option><option value="#eeddb8">Vanila</option></select><label for="card-message">Kartu ucapan (maksimal 80 karakter)</label><input id="card-message" maxlength="80" value="Semoga harimu mekar indah ♡"><div class="demo-actions"><button class="button secondary" id="bouquet-reset">Ulangi rangkaian</button></div>`;
 const update=()=>{document.querySelector('#bouquet-preview').style.setProperty('--wrap',document.querySelector('#wrap-color').value);document.querySelector('#bouquet-message').textContent=document.querySelector('#card-message').value.trim()||'Buket kecil untukmu ♡';};
 document.querySelector('#wrap-color').addEventListener('change',update);document.querySelector('#card-message').addEventListener('input',update);document.querySelector('#bouquet-reset').addEventListener('click',()=>{document.querySelector('#wrap-color').value='#f0bfd2';document.querySelector('#card-message').value='Semoga harimu mekar indah ♡';update();});
 }else if(kind==='memory'){
 title.textContent='Kelopak Kembar';
 content.innerHTML='<p>Buka dua kartu. Temukan empat pasangan bunga yang sama.</p><div id="memory-status" class="game-status" role="status">0 langkah · 0 dari 4 pasangan</div><div class="memory-grid" id="memory-grid"></div><button id="memory-reset" class="button secondary">Acak & main lagi</button>';
 let cards=[],selected=[],pairs=0,moves=0,locked=false,timer;const names={'🌸':'Sakura','🌷':'Tulip','🌻':'Bunga matahari','🌼':'Daisy'};
 const status=()=>{document.querySelector('#memory-status').textContent=pairs===4?`Taman lengkap! Semua pasangan ditemukan dalam ${moves} langkah.`:`${moves} langkah · ${pairs} dari 4 pasangan`;};
 const start=()=>{clearTimeout(timer);cards=['🌸','🌷','🌻','🌼','🌸','🌷','🌻','🌼'];for(let i=cards.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[cards[i],cards[j]]=[cards[j],cards[i]];}selected=[];pairs=0;moves=0;locked=false;status();const grid=document.querySelector('#memory-grid');grid.replaceChildren();cards.forEach((symbol,i)=>{const b=document.createElement('button');b.textContent='✿';b.type='button';b.setAttribute('aria-label',`Buka kartu ${i+1}`);b.addEventListener('click',()=>{if(locked||b.classList.contains('matched')||selected.some(x=>x.i===i))return;b.textContent=symbol;b.setAttribute('aria-label',`Kartu ${i+1}: ${names[symbol]}`);selected.push({i,b});if(selected.length===2){moves++;if(cards[selected[0].i]===cards[selected[1].i]){selected.forEach(x=>{x.b.classList.add('matched');x.b.setAttribute('aria-disabled','true');});pairs++;selected=[];status();}else{locked=true;status();timer=setTimeout(()=>{selected.forEach(x=>{x.b.textContent='✿';x.b.setAttribute('aria-label',`Buka kartu ${x.i+1}`);});selected=[];locked=false;},850);}}});grid.append(b);});};
 document.querySelector('#memory-reset').addEventListener('click',start);cleanup=()=>clearTimeout(timer);start();
 }else if(kind==='garden'){
 title.textContent='Lily Kecilku';content.innerHTML='<p>Demo pertumbuhan sederhana: bunga membutuhkan 3 tetes air dan 3 sinar matahari. Tidak ada hitungan waktu.</p><div class="demo-preview"><div class="garden-stage" id="garden-stage" aria-hidden="true">🌱</div><div id="garden-status" role="status">Tunas baru · air 0/3 · cahaya 0/3</div><progress class="garden-meter" id="garden-meter" value="0" max="6" aria-label="Pertumbuhan bunga">0/6</progress></div><div class="demo-actions"><button class="button" id="give-water">💧 Beri air</button><button class="button secondary" id="give-light">☀ Beri cahaya</button><button class="button secondary" id="garden-reset">Tanam lagi</button></div>';
 let water=0,light=0;const update=()=>{const total=water+light;document.querySelector('#garden-meter').value=total;document.querySelector('#give-water').disabled=water===3;document.querySelector('#give-light').disabled=light===3;document.querySelector('#garden-status').textContent=`${total===6?'Lily mekar! Terima kasih sudah merawatnya ♡':total>=3?'Mulai bertumbuh':'Tunas baru'} · air ${water}/3 · cahaya ${light}/3`;const stage=document.querySelector('#garden-stage');stage.replaceChildren();if(total===6){const img=document.createElement('img');img.src='assets/lily.svg';img.alt='';stage.append(img);}else stage.textContent=total>=3?'🌿':'🌱';};document.querySelector('#give-water').addEventListener('click',()=>{water=Math.min(3,water+1);update();});document.querySelector('#give-light').addEventListener('click',()=>{light=Math.min(3,light+1);update();});document.querySelector('#garden-reset').addEventListener('click',()=>{water=light=0;update();});
 }
 }
 document.querySelectorAll('[data-demo]').forEach(button=>{button.hidden=false;button.addEventListener('click',()=>{cleanup();cleanup=()=>{};opener=button;setup(button.dataset.demo);dialog.showModal();});});
})();
